### ISSUE TITLE
Support "custom" commands, and represent `\pmod` this way

### ISSUE THREAD

**Issue by tmke8** [tmke8/latex2mmlc#211]
`\pmod` should not have its own AST node, because it can just be assembled out of existing nodes.

**Comment by tmke8** [comment]
These are the kinds of things we should support, though I don't think we need to actually parse the latex for this; just some kind of config format:

```latex
    \\newcommand\\d[0]{\\operatorname{d}\\!}
    \\def\\foo{x^2}
    \\definecolor{sortaGreen}{RGB}{128,128,0}
```

**Comment by tmke8** [comment]
Ideas for a config file:

```yaml
newcommands:
  d: "\operatorname{d}\!"
defs:
  foo: "x^2"
colors:
  sortaGreen:
    RGB:
      - 128
      - 128
      - 0
```

**Comment by tmke8** [comment]
Though, internally, you'd want to store this as a hashmap, so maybe it should be like this after all:

```yaml
newcommands:
  RR:
    args: 0
    expansion: "\\mathbb{R}"
  bb:
    args: 1
    expansion: "\\mathbb{#1}"
  foo:
    args: 0
    expansion: "x^2"
colors:
  sortaGreen:
    rgb:
      - 128
      - 128
      - 0
```
Though maybe we can just insert it into the hashmap this way while still having the config file as above.

**Comment by tmke8** [comment]
Hmm, commands that take arguments are tricky. Here is I think what you'd want to do:

- when encountering a custom command, stop parsing for now
- extract its arguments as string slices
- construct a String that is the "expansion" string but with the placeholders replaced by the arguments we extracted in the previous step
- parse this String

This would require some re-architecturing of the parser.

**Comment by tmke8** [comment]
KaTeX also allows specifying macros in the configuration: https://katex.org/docs/options (look for "macros").

**Comment by tmke8** [comment]
Maybe `PredefNode` could store

```
tf: Option<TextTransform>,
var: Option<MathVariant>,
```

And then there are nodes in the predefined AST which have alternative values depending on `tf` and `var`...

But there are too many possibilities, no? And I might later add global state like `after_a_relation: bool`.

**Comment by tmke8** [comment]
To build on the previous comment, I shouldn't try to record all possible values but rather store the necessary information to determine the right value when given `tf` and `var`.

Here is something that would work but would not be that efficient:

We add a new global flag to the parser. This flag indicates whether or not we're recording a macro right now. if we are recording a macro then at the point where the transformation or the variant is needed, we don't record a node but a closure that takes in the transformation and the variance. Then, during rendering, the closure is called.

**Comment by tmke8** [comment]
But what about something like

```yaml
  - name: bb
    args: 1
    expansion: "\\mathbb{#1}"
```
Now the recorded macro needs to set `tf`.
