### ISSUE TITLE
Try to fix superscript positioning on Chrome with global CSS

### ISSUE THREAD

**Issue by tmke8** [tmke8/latex2mmlc#267]
Looking at the Temml CSS, I only see padding for primes, but it affects all superscripts, right?

**Comment by tmke8** [comment]
This seems to work:

```css
msup > :not(:first-child) {
    margin-left: 0.15em;
}
```
